apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DATABASE_URL: 'postgresql://myapp_user:change_me_please@postgres-0.postgres.default.svc.cluster.local:5432/myapp'
  DB_USER: 'myapp_user'
  DB_PASSWORD: 'change_me_please'
