apiVersion: 1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
    - name: backend
      image: node:20-alpine
      ports:
        - containerPort: 3000
      command: ['node', 'server.js']
