apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
        - name: backend-api
          image: abazuntts/backend:sha-42fa3a129f1a1f806d6914509f1b970ca29efdd4
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: postgresql://myapp_user:change_me_please@postgres.default.svc.cluster.local:5432/myapp


