name: Deploy

on:
  push:
    branches: [main]

jobs:
  # checks:
  #   uses: ./.github/workflows/pr-check.yml

  build:
    # needs: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: DockerHub Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Build and push
        env:
          IMAGE_SHA: ${{ secrets.DOCKER_USER }}/backend:sha-${{ github.sha }}
          IMAGE_LATEST: ${{ secrets.DOCKER_USER }}/backend:latest
        run: |
          docker build -t $IMAGE_SHA -t $IMAGE_LATEST .
          docker push $IMAGE_SHA
          docker push $IMAGE_LATEST
  # deploy:
  #   needs: checks
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy via SSH
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USER }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         script: |
  #           cd /var/www/myapp/backend
  #           git pull origin main
  #           cd /var/www/myapp
  #           docker compose up -d --build backend
  # notify:
  #   needs: [checks, deploy]
  #   if: always()
  #   uses: ./.github/workflows/notify.yml
